apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-todo-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flask-todo
  endpoints:
  - port: http
    path: /metrics