apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-ns
spec:
  selector: 
    name: todo-app
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007 # Pick a port in 30000-32767
